name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login DockerHub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

    - name: Build Backend
      run: docker build -t ${{ secrets.DOCKER_USER }}/pastaquest-backend -f backend/Dockerfile .

    - name: Build Frontend
      run: docker build -t ${{ secrets.DOCKER_USER }}/pastaquest-frontend -f frontend/Dockerfile .

    - name: Push Images
      run: |
        docker push ${{ secrets.DOCKER_USER }}/pastaquest-backend
        docker push ${{ secrets.DOCKER_USER }}/pastaquest-frontend
