name: CI/CD DevOps PastaQuest

on:
  push:
    branches:
      - main

jobs:
  # =====================
  # 1️⃣ BUILD & PUSH BACKEND ET FRONTEND
  # =====================
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # BACKEND IMAGE
      - name: Build backend image
        run: docker build -f backend/Dockerfile -t hamdihend/pastaquest-backend .

      - name: Push backend image
        run: docker push hamdihend/pastaquest-backend

      # FRONTEND IMAGE
      - name: Build frontend image
        run: docker build -f frontend/Dockerfile -t hamdihend/pastaquest-frontend .

      - name: Push frontend image
        run: docker push hamdihend/pastaquest-frontend

  # =====================
  # 2️⃣ DEPLOY BACKEND TO AZURE
  # =====================
  deploy-backend:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: pastaquest-backend
          images: hamdihend/pastaquest-backend

  # =====================
  # 3️⃣ DEPLOY FRONTEND TO AZURE
  # =====================
  deploy-frontend:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: pastaquest-frontend
          images: hamdihend/pastaquest-frontend
