name: CI/CD DevOps PastaQuest

on:
  push:
    branches:
      - main

jobs:
  # =====================
  # 1️⃣ BUILD & PUSH BACKEND ET FRONTEND
  # =====================
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login Docker
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Backend
      - name: Build Backend Image
        run: docker build -f backend/Dockerfile -t hamdihend/pastaquest-backend:latest .

      # Build Frontend
      - name: Build Frontend Image
        run: docker build -f frontend/Dockerfile -t hamdihend/pastaquest-frontend:latest .

      # Push Backend
      - name: Push Backend Image
        run: docker push hamdihend/pastaquest-backend:latest

      # Push Frontend
      - name: Push Frontend Image
        run: docker push hamdihend/pastaquest-frontend:latest
# =====================
# 2️⃣ BUILD & PUSH FRONTEND
# =====================
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend Image
        run: |
          docker build -f frontend/Dockerfile -t hamdihend/pastaquest-frontend:latest .

      - name: Push Frontend Image
        run: |
          docker push hamdihend/pastaquest-frontend:latest

# =====================
# 3️⃣ DEPLOY BACKEND
# =====================
  deploy-backend:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: pastaquest-backend
          images: hamdihend/pastaquest-backend:latest

# =====================
# 4️⃣ DEPLOY FRONTEND
# =====================
  deploy-frontend:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Frontend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: pastaquest-frontend
          images: hamdihend/pastaquest-frontend:latest
